# Generated by Django 5.2.17 on 2026-08-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=120)),
                ('level', models.CharField(choices=[('Pemula', 'Pemula'), ('Menengah', 'Menengah'), ('Lanjutan', 'Lanjutan')], default='Pemula', max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Durasi dalam jam')),
                ('students', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accent', models.CharField(default='teal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
